### ISSUE TITLE
Supporting metadata in the JWT payload

### ISSUE THREAD

**Issue by Dorian** [dreimannzelt/layer-identity_token#4]
There is a whitelist that doesn't include the `metadata` key:

```
SUPPORTED_CLAIM_ATTRIBUTES = %w(first_name last_name display_name avatar_url)
```

Do you have any particular concern against supporting the `metadata` key?

- Code: https://github.com/dreimannzelt/layer-identity_token/blob/master/lib/layer/identity_token.rb#L23
- Docs: https://docs.layer.com/reference/server_api/identity.obj

**Comment by we5** [comment]
@Dorian hey, thanks for reaching out. No, we do not have any particular concern against this. For me I cannot find any real reason to not support it, what about your opinion @benedikt?

**Comment by benedikt** [comment]
Let's do it! :)
